store/cart/urls.py
from django.urls import path
from .views import CartView


app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
]

store/ordering/urls.py
from django.urls import path
from .views import OrderViewStep1, OrderViewStep2, OrderViewStep3, OrderViewStep4, PaymentOnlineCardView, PaymentSomeoneCardView, OrderDetails


app_name = 'order'

urlpatterns = [
    path('step-1/', OrderViewStep1.as_view(), name='step_1'),
    path('step-2/', OrderViewStep2.as_view(), name='step_2'),
    path('step-3/', OrderViewStep3.as_view(), name='step_3'),
    path('step-4/', OrderViewStep4.as_view(), name='step_4'),
    path('payment-online/', PaymentOnlineCardView.as_view(), name='payment_online'),
    path('payment-someone/', PaymentSomeoneCardView.as_view(), name='payment_someone'),
    path('details/<int:pk>/', OrderDetails.as_view(), name='order_details'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from my_store_app.views import CategoryView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user-auth/', include("user_app.urls")),
    path('catalog/', include("catalog.urls")),
    path('cart/', include("cart.urls")),
    path('details/', include("product_details.urls")),
    path('private-office/', include("private_office.urls")),
    path('order/', include("ordering.urls")),
    path('', CategoryView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/user_app/urls.py
from django.urls import path
from .views import (Login, AuthorLogoutView, RegisterCustomerView, FirstRegisterSellerView, SecondRegisterSellerView,
                    RestorePasswordFirstStep,
                    RestorePasswordSecondStep)


app_name = 'user_app'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', AuthorLogoutView.as_view(), name='logout'),
    path('register/customer/', RegisterCustomerView.as_view(), name='register_customer'),
    path('register/seller/first-step', FirstRegisterSellerView.as_view(), name='register_seller_step_one'),
    path('register/seller/second-step', SecondRegisterSellerView.as_view(), name='register_seller_step_two'),
    path('register/drop-password/first-step/', RestorePasswordFirstStep.as_view(), name='password_first'),
    path('register/drop-password/second-step/', RestorePasswordSecondStep.as_view(), name='password_second'),
]

store/ordering/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from cart.models import Basket
from django.contrib.auth import get_user_model


class Order(models.Model):

    STATUS_CHOICES = [
        ('not_paid', 'Не оплачено'),
        ('paid', 'Оплачен'),
        ('error', 'Ошибка'),
    ]

    PAY_METHOD_CHOICES = [
        ('online_card', 'Онлайн картой'),
        ('random_check', 'Онлайн со случайного чужого счета'),
    ]

    DELIVERY_METHOD_CHOICES = [
        ('common', 'Обычная доставка'),
        ('express', 'Экспресс-доставка'),
    ]

    name = models.CharField(max_length=50, verbose_name='Имя')
    family_name = models.CharField(max_length=50, verbose_name='Фамилия')
    surname = models.CharField(max_length=50, verbose_name='Отчество', blank=True)
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, verbose_name='Активный пользователь',
                                       related_name='order', blank=True, null=True, help_text='Пользователь, на котором в данный момент закреплён заказ')
    total_price = models.DecimalField(verbose_name='Общая сумма', max_digits=10, decimal_places=2)
    phone = models.CharField(max_length=30, verbose_name='номер телефона')
    email = models.EmailField(verbose_name='email пользователя')
    delivery_method = models.CharField(verbose_name='Способ доставки', blank=True, max_length=100,
                                       choices=DELIVERY_METHOD_CHOICES)
    city = models.CharField(verbose_name='Город доставки', blank=True, max_length=100)
    address = models.CharField(verbose_name='Адрес доставки', blank=True, max_length=250)
    pay_method = models.CharField(blank=True, max_length=100, choices=PAY_METHOD_CHOICES, verbose_name='Метод оплаты')
    comment = models.CharField(blank=True, max_length=350, verbose_name='Комментарий к заказу')
    delivery_price = models.SmallIntegerField(default=0, verbose_name='Сумма на доставку')
    status = models.CharField(verbose_name='Статус заказа', choices=STATUS_CHOICES, max_length=100)
    error_message = models.CharField(verbose_name='Описание ошибки оплаты', max_length=250, blank=True)
    history_user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Архивный пользователь',
                                     blank=True, null=True, related_name='history_order')
    payment_date = models.DateTimeField(blank=True, verbose_name='Дата оплаты заказа')
    basket_objects = models.ManyToManyField(blank=True, verbose_name='Корзина заказа', related_name='order', to=Basket)
    archived = models.BooleanField(default=False, verbose_name='Архивированно/Заказ выполнен')

    def get_absolute_url(self):
        return reverse('order:order_details', kwargs={'pk': self.id})

    def clean(self):
        if not self.archived and Order.objects.filter(models.Q(email=self.email) | models.Q(phone=self.phone), archived=False).exclude(id=self.pk).exists():
            raise ValidationError('Активный заказ с таким номером телефона или email-почтой уже существует.')

store/ordering/forms.py
from django import forms
from ordering.models import Order


class OrderStep1Form(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['name', 'family_name', 'surname', 'phone', 'email']


class OrderStep1FormIfNotLogin(forms.Form):
    login = forms.CharField(label='Имя пользователя', max_length=50)
    password = forms.CharField(widget=forms.PasswordInput(), label='Пароль', required=True)
    password2 = forms.CharField(widget=forms.PasswordInput(), label='Повторите пароль', required=True)


class DeliveryAddressForm(forms.Form):
    MY_CHOICES = [
        ('common', 'Обычная доставка'),
        ('express', 'Экспресс-доставка'),
    ]

    delivery = forms.CharField(widget=forms.RadioSelect(choices=MY_CHOICES))
    city = forms.CharField(max_length=100, label='Город', widget=forms.TextInput(attrs={'class': 'form-input'}))
    address = forms.CharField(max_length=150, widget=forms.Textarea(attrs={'class': 'form-textarea', 'rows': 1, 'cols': 15}), label='Адрес')


class PayMethodForm(forms.Form):
    MY_CHOICES = [
        ('online_card', 'Онлайн картой'),
        ('random_check', 'Онлайн со случайного чужого счета'),
    ]

    pay = forms.CharField(widget=forms.RadioSelect(choices=MY_CHOICES))


class CommentForm(forms.Form):
    comment = forms.CharField(max_length=350, label='Комментарий к заказу', widget=forms.Textarea(attrs={'class': 'full', 'rows': 4}))

store/ordering/views.py
from datetime import datetime
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.db import IntegrityError
from django.db.models import Sum, F
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView
from cart.models import Basket
from cart.service import CartService
from customers_sellers.models import Profile
from my_store_app.utils import total_sum_and_quantity_update_context
from .forms import OrderStep1FormIfNotLogin, OrderStep1Form, DeliveryAddressForm, PayMethodForm
from .models import Order
from .utils import add_order_step_permission_to_user, delete_permissions
from django.forms.models import model_to_dict
from .forms import CommentForm
from .service import PaymentService


class OrderViewStep1(View):
    def get(self, request, **kwargs):
        cart_service = CartService(request=request)


        queryset = cart_service.get_list_of_products_in_cart(request=request)
        if not queryset:
            url = reverse('cart:cart') + '#empty_basket'
            return redirect(url)
        elif not isinstance(queryset.first(), Basket):
            queryset = None

        if 'non_field_error_name' in kwargs:
            user_form = kwargs['non_field_error_name']
        elif request.user.is_authenticated and hasattr(request.user, 'order'):
            order = request.user.order
            #order_dict = model_to_dict(order, fields=['name', 'family_name', 'surname', 'phone', 'email'])
            user_form = OrderStep1Form(instance=order)
        elif request.user.is_authenticated:
            profile = request.user.customer.profile
            profile_dict = model_to_dict(profile, fields=['name', 'family_name', 'surname', 'phone', 'email'])
            user_form = OrderStep1Form(profile_dict)
        else:
            user_form = OrderStep1Form()

        if 'error_password' in request.session:
            auth_form = OrderStep1FormIfNotLogin(request.session['error_password'])
            auth_form.add_error('password', 'Пароли не совпадают')
            del request.session['error_password']
        else:
            auth_form = OrderStep1FormIfNotLogin()

        context = {
            'step': 1,
            'auth_form': auth_form,
            'user_form': user_form,
            'login_form': AuthenticationForm(),
        }

        total_sum_and_quantity_update_context(context=context, request=request, queryset_for_cart_table=queryset)

        return render(request, 'ordering/order_step_1.html', context=context)

    def post(self, request):
        values = request.POST.dict()
        values['phone'] = values.get('phone')[3:].replace(')', '-')

        form = OrderStep1Form(values, instance=request.user.order) if hasattr(request.user, 'order') else OrderStep1Form(values)

        if request.POST.get('name') == Profile._meta.get_field('name').default or request.POST.get('family_name') == Profile._meta.get_field('family_name').default:
            form.add_error(None, 'Нужно указать фамилию и имя!')

        if form.is_valid():
            total = round(Basket.objects.filter(user=request.user, archived=False).aggregate(total=Sum(F('product__price') * F('quantity')))['total'], 2)
            surname = '' if form.cleaned_data.get('surname') == Profile._meta.get_field('surname').default else form.cleaned_data.get('surname')
            if not Order.objects.filter(user=request.user, archived=False).exists():
                Order.objects.create(user=request.user, phone=form.cleaned_data.get('phone'),
                                     total_price=total, surname=surname,
                                     name=form.cleaned_data.get('name'),
                                     family_name=form.cleaned_data.get('family_name'),
                                     email=form.cleaned_data.get('email'),
                                     status='not_paid', payment_date=datetime.now())
            else:
                Order.objects.filter(user=request.user, archived=False).update(phone=form.cleaned_data.get('phone'), total_price=total,
                                                               surname=surname, name=form.cleaned_data.get('name'),
                                                               family_name=form.cleaned_data.get('family_name'),
                                                               email=form.cleaned_data.get('email'),
                                                               status='not_paid', payment_date=datetime.now())

            # Добавление разрешения на продолжение оформления заказа
            add_order_step_permission_to_user(request=request, codename='step_order_permission_2')

            return redirect(reverse('order:step_2'))

        return self.get(request, non_field_error_name=form)




class OrderViewStep2(PermissionRequiredMixin, View):
    permission_required = 'ordering.step_order_permission_2'

    def get(self, request):
        cart_service = CartService(request=request)

        order = request.user.order
        delivery_dict = model_to_dict(order, fields=['address', 'city'])

        context = {
            'step': 2,
            'form': DeliveryAddressForm(delivery_dict),
        }
        queryset = cart_service.get_list_of_products_in_cart(request=request)
        total_sum_and_quantity_update_context(context=context, request=request, queryset_for_cart_table=queryset)

        return render(request, 'ordering/order_step_2.html', context=context)


    def post(self, request):
        form = DeliveryAddressForm(request.POST)
        if form.is_valid():
            order = request.user.order

            if order.delivery_price:
                order.total_price -= order.delivery_price
                order.save()

            delivery_method = request.POST.get('delivery')
            if delivery_method == 'common':
                if order.total_price < settings.FREE_DELIVERY_BORDER:
                    order.total_price += settings.COMMON_DELIVERY_PRICE
                    order.delivery_price = settings.COMMON_DELIVERY_PRICE
                order.delivery_method = delivery_method
            elif delivery_method == 'express':
                order.total_price += settings.EXPRESS_DELIVERY_PRICE
                order.delivery_method = delivery_method
                order.delivery_price = settings.EXPRESS_DELIVERY_PRICE
            else:
                return self.get(request=request)

            order.city = request.POST.get('city')
            order.address = request.POST.get('address')
            order.save()

            # Добавление разрешения на продолжение оформления заказа
            add_order_step_permission_to_user(request=request, codename='step_order_permission_3')

            return redirect(reverse('order:step_3'))

        return self.get(request=request)


class OrderViewStep3(PermissionRequiredMixin, View):
    permission_required = 'ordering.step_order_permission_3'

    def get(self, request):
        cart_service = CartService(request=request)

        context = {
            'step': 3,
            'form': PayMethodForm(),
        }
        queryset = cart_service.get_list_of_products_in_cart(request=request)
        total_sum_and_quantity_update_context(context=context, request=request, queryset_for_cart_table=queryset)

        return render(request, 'ordering/order_step_3.html', context=context)

    def post(self, request):
        order = request.user.order
        form = PayMethodForm(request.POST)
        if form.is_valid():
            pay_method = request.POST.get('pay')
            if pay_method == 'online_card':
                order.pay_method = pay_method
            elif pay_method == 'random_check':
                order.pay_method = pay_method
            else:
                return self.get(request=request)

            order.save()

            # Добавление разрешения на продолжение оформления заказа
            add_order_step_permission_to_user(request=request, codename='step_order_permission_4')

            return redirect(reverse('order:step_4'))

        return self.get(request=request)


class OrderViewStep4(PermissionRequiredMixin, View):
    permission_required = 'ordering.step_order_permission_4'

    def get(self, request, **kwargs):
        cart_service = CartService(request=request)

        if 'comment_error' in kwargs:
            comment_form = kwargs['comment_error']
        else:
            comment_form = CommentForm()

        queryset = cart_service.get_list_of_products_in_cart(request=request)
        context = {
            'step': 4,
            'order': request.user.order,
            'basket': queryset,
            'comment_form': comment_form,
        }
        total_sum_and_quantity_update_context(context=context, request=request, queryset_for_cart_table=queryset)

        return render(request, 'ordering/order_step_4.html', context=context)

    def post(self, request):
        if 'comment' in request.POST:
            comment = request.POST.get('comment')
            form = CommentForm(request.POST)
            if form.is_valid():
                order = request.user.order
                order.comment = comment
                order.save()
                return self.get(request=request)
            return self.get(request=request, comment_error=form)
        elif 'payment' in request.POST:
            order = request.user.order
            codename_online_card = 'order_payment_permission_online_card'
            codename_someone_card = 'order_payment_permission_someone_card'

            # Добавление разрешения на оплату заказа и удаления (если существует) другого разрешения на оплату
            if order.pay_method == 'online_card':

store/ordering/templates/ordering/oneorder.html
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->

<head>
    <title>Megano</title>
    {% include 'includes/header.html' %}
</head>

<body class="Site">
    <!--if lt IE 8
  p.error-browser
      | Ваш браузер&nbsp;
      em устарел!&nbsp;
      a(href="http://browsehappy.com/") Выберите новую версию
          +s
          | браузера здесь&nbsp;
      | для правильного отображения сайта.
  -->
    <header class="Header">
        {% include 'includes/head_line.html' %}
        {% include 'includes/top-menu-and-logo.html' %}
        {% include 'includes/search-line.html' %}
    </header>
    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">Заказ №{{ order.id }}</h1>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                <div class="Section-content">
                    <div class="Orders"></div>
                    <div class="Order">
                        <div class="Order-infoBlock">
                            <div class="Order-personal">
                                <div class="row">
                                    <div class="row-block">
                                        <div class="Order-info Order-info_date">
                                            <div class="Order-infoType">Дата заказа:</div>
                                            <div class="Order-infoContent">{{ order.payment_date|date:"d.m.Y" }}</div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">ФИО:</div>
                                            <div class="Order-infoContent">{{ order.name }} {{ order.family_name }} {% firstof order.surname '' %}</div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">Телефон:</div>
                                            <div class="Order-infoContent">+7-{{ order.phone }}</div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">E-mail:</div>
                                            <div class="Order-infoContent">{{ order.email }}</div>
                                        </div>
                                    </div>
                                    <div class="row-block">
                                        <div class="Order-info Order-info_delivery">
                                            <div class="Order-infoType">Тип доставки:</div>
                                            <div class="Order-infoContent">{{ order.get_delivery_method_display }}{% if order.delivery_price %}(+{{ order.delivery_price }}р){% endif %}</div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">Город:</div>
                                            <div class="Order-infoContent">{{ order.city }}</div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">Адрес:</div>
                                            <div class="Order-infoContent">{{ order.address }}</div>
                                        </div>
                                        <div class="Order-info Order-info_pay">
                                            <div class="Order-infoType">Оплата:</div>
                                            <div class="Order-infoContent">{{ order.get_pay_method_display }}</div>
                                        </div>
                                        <div class="Order-info Order-info_status">
                                            <div class="Order-infoType">Статус:</div>
                                            <div class="Order-infoContent">{{ order.get_status_display }}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="Cart Cart_order">
                                {% for product in order.basket_objects.all %}
                                {% with product_obj=product.product.product %}
                                <div class="Cart-product">
                                    <div class="Cart-block Cart-block_row">
                                        {% if product_obj.title_picture %}
                                        <div class="Cart-block Cart-block_pict">
                                            <a class="Cart-pict" href="{{ product_obj.get_absolute_url }}">
                                                <img class="Cart-img"
                                                     src="{{ product_obj.title_picture.url }}"
                                                     alt="card.jpg" />
                                            </a>
                                        </div>
                                        {% endif %}
                                        <div class="Cart-block Cart-block_info">
                                            <a class="Cart-title"
                                               href="{{ product_obj.get_absolute_url }}">{{ product_obj.title }}</a>
                                            <div class="Cart-desc">{{ product_obj.description }}</div>
                                        </div>
                                        <div class="Cart-block Cart-block_price">
                                            <div class="Cart-price">{{ product.product.price }}$</div>
                                        </div>
                                    </div>
                                    <div class="Cart-block Cart-block_row">
                                        <div class="Cart-block Cart-block_amount">{{ product.quantity }} шт.</div>
                                    </div>
                                </div>
                                {% endwith %}
                                {% endfor %}
                                <div class="Cart-total">
                                    <div class="Cart-block Cart-block_total">
                                        <strong class="Cart-title">Итого:<span class="Cart-price">{{ order.total_price }}$</span></strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'includes/footer.html' %}
    <!--+Middle-->
    <!--    +div.-top-->
    <!--        +breadcrumbs('Главная','Портфолио')-->
    <!--    +Article('portfolio')-->
    <!---->
    {% include 'includes/bottom_scripts.html' %}
</body>

</html>

store/ordering/templates/ordering/order_step_2.html
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->

{% load my_tags %}

<head>
    <title>Megano</title>
    {% include 'includes/header.html' %}
</head>

<body class="Site">
    <!--if lt IE 8
  p.error-browser
      | Ваш браузер&nbsp;
      em устарел!&nbsp;
      a(href="http://browsehappy.com/") Выберите новую версию
          +s
          | браузера здесь&nbsp;
      | для правильного отображения сайта.
  -->
    <header class="Header">
        {% include 'includes/head_line.html' %}
        {% include 'includes/top-menu-and-logo.html' %}
        {% include 'includes/search-line.html' %}
    </header>
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnRight Section_columnWide Order">
            <div class="wrap">

                {% ordering_menu pointer=step %}

                <div class="Section-content">
                    <form method="post" class="form">
                        <header class="Section-header Section-header_sm">
                            <h2 class="Section-title">Шаг 2. Способ доставки</h2>
                        </header>

                        {% for row in form %}
                        <div class="form-group">
                            {% if forloop.counter == 1 %}
                                {% for i in row %}
                                    <div>
                                        <label class="toggle">
                                            {{ i.tag }}<span class="toggle-box"></span><span class="toggle-text">{{ i.choice_label }}</span>
                                        </label>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <label class="form-label" for="{{ row.id_for_label }}">{{ row.label }}</label>
                                {{ row }}
                            {% endif %}
                        </div>
                        {% endfor %}

                        <div class="Order-footer">
                            {% csrf_token %}
                            <button type="submit" class="btn btn_success">Дальше</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% include 'includes/footer.html' %}
    <!--+Middle-->
    <!--    +div.-top-->
    <!--        +breadcrumbs('Главная','Портфолио')-->
    <!--    +Article('portfolio')-->
    <!---->
    {% include 'includes/bottom_scripts.html' %}
</body>

</html>

store/ordering/templates/ordering/order_step_3.html
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->

{% load my_tags %}

<head>
    <title>Megano</title>
    {% include 'includes/header.html' %}
</head>

<body class="Site">
    <!--if lt IE 8
  p.error-browser
      | Ваш браузер&nbsp;
      em устарел!&nbsp;
      a(href="http://browsehappy.com/") Выберите новую версию
          +s
          | браузера здесь&nbsp;
      | для правильного отображения сайта.
  -->
    <header class="Header">
        {% include 'includes/head_line.html' %}
        {% include 'includes/top-menu-and-logo.html' %}
        {% include 'includes/search-line.html' %}
    </header>
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnRight Section_columnWide Order">
            <div class="wrap">

                {% ordering_menu pointer=step %}

                <div class="Section-content">
                    <form method="post" class="form">
                        <header class="Section-header Section-header_sm">
                            <h2 class="Section-title">Шаг 3. Способ оплаты</h2>
                        </header>
                        <div class="form-group">

                            {% for field in form.pay %}
                                <div>
                                    <label class="toggle">
                                       {{ field.tag }}<span class="toggle-box"></span><span class="toggle-text">{{ field.choice_label }}</span>
                                    </label>
                                </div>
                            {% endfor %}

                        </div>
                        <div class="Order-footer">
                            {% csrf_token %}
                            <button type="submit" class="btn btn_success">Дальше</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% include 'includes/footer.html' %}
    <!--+Middle-->
    <!--    +div.-top-->
    <!--        +breadcrumbs('Главная','Портфолио')-->
    <!--    +Article('portfolio')-->
    <!---->
    {% include 'includes/bottom_scripts.html' %}
</body>

</html>