store/cart/urls.py
from django.urls import path
from .views import CartView


app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
]

store/catalog/urls.py
from django.urls import path
from .views import CatalogView


app_name = 'catalog'

urlpatterns = [
    path('', CatalogView.as_view(), name='catalog'),
]

store/my_store_app/urls.py
from django.urls import path


app_name = 'store'

urlpatterns = [

]

store/private_office/urls.py
from django.urls import path
from .views import office, profile, HistoryView, delete_avatar


app_name = 'private_office'

urlpatterns = [
    path('', office, name='office'),
    path('profile/', profile, name='profile'),
    path('history/', HistoryView.as_view(), name='history'),
    path('del-avatar/', delete_avatar, name='del_avatar'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from my_store_app.views import CategoryView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user-auth/', include("user_app.urls")),
    path('catalog/', include("catalog.urls")),
    path('cart/', include("cart.urls")),
    path('details/', include("product_details.urls")),
    path('private-office/', include("private_office.urls")),
    path('order/', include("ordering.urls")),
    path('', CategoryView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/user_app/urls.py
from django.urls import path
from .views import (Login, AuthorLogoutView, RegisterCustomerView, FirstRegisterSellerView, SecondRegisterSellerView,
                    RestorePasswordFirstStep,
                    RestorePasswordSecondStep)


app_name = 'user_app'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', AuthorLogoutView.as_view(), name='logout'),
    path('register/customer/', RegisterCustomerView.as_view(), name='register_customer'),
    path('register/seller/first-step', FirstRegisterSellerView.as_view(), name='register_seller_step_one'),
    path('register/seller/second-step', SecondRegisterSellerView.as_view(), name='register_seller_step_two'),
    path('register/drop-password/first-step/', RestorePasswordFirstStep.as_view(), name='password_first'),
    path('register/drop-password/second-step/', RestorePasswordSecondStep.as_view(), name='password_second'),
]

store/my_store_app/models.py
from django.contrib.auth.models import User
from django.db import models
from .utils import validate_image, GetUploadPath


class UrlRoad(models.Model):
    """Модель для хранения всех url путей на сайте"""

    category = models.CharField(max_length=150)
    page = models.CharField(max_length=150, blank=True)
    description = models.CharField(max_length=200, blank=True)
    http_method = models.CharField(max_length=50)
    url = models.URLField(max_length=255, unique=True)
    comment = models.TextField(default='--')


class SiteConfiguration(models.Model):
    logo_image = models.ImageField(upload_to='logo/', verbose_name='Картинка логотипа', blank=True)
    contact_number = models.CharField(max_length=20, verbose_name='Контактный телефон', blank=True)
    contact_email = models.EmailField(verbose_name='Контактный e-mail', blank=True)

    @classmethod
    def get_config(cls):
        cong, _ = cls.objects.get_or_create(id=1)
        return cong

    class Meta:
        verbose_name = 'Конфигурации сайта'
        verbose_name_plural = 'Конфигурации сайта'

store/my_store_app/views.py
from django.db.models import Avg
from django.http import HttpRequest
from django.shortcuts import render
from django.views import View
from my_store_app.utils import get_active_categories, total_sum_and_quantity_update_context,\
    get_product_shop_with_min_price, round_total_sum
from goods.models import Product
from cart.service import CartService


class CategoryView(View):
    """Формирование списка категорий, популярных товаров,
         лимитированных, баннеров и путей до изображений этих категорий"""

    def get(self, request: HttpRequest):
        cart_service = CartService(request)

        popular_product = Product.objects.filter(
                is_active=True
            ).annotate(avg_price=Avg('products__price')).order_by('-purchase_count')[:8]
        round_total_sum(list_of_products=popular_product, field='avg_price')

        context = {
            'popular_product': popular_product,                                                     # 8 популярных продуктов
        }

        if request.user.is_authenticated:
            queryset = cart_service.get_list_of_products_in_cart(request=request)
        else:
            queryset = None

        total_sum_and_quantity_update_context(context=context, request=request, queryset_for_cart_table=queryset)       # Обновление context

        return render(request, 'index.html', context=context)

    def post(self, request: HttpRequest, *args, **kwargs):
        service = CartService(request)
        product_shop = get_product_shop_with_min_price(request=request)

        service.add_product_to_cart(product_shop=product_shop, request=request)
        return self.get(request)

store/my_store_app/templates/includes/bottom_scripts.html
{% load static %}

<script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
<script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
<script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
<script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
<script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
<script src="{% static 'assets/js/scripts.js' %}"></script>

store/my_store_app/templates/includes/footer.html
{% load static %}

<footer class="Footer">
    <div class="wrap">
        <div class="row Footer-main">
            <div class="row-block">
                <a class="logo Footer-logo" href="{% url 'index' %}">
                    <img class="logo-image" src="{% if configurations.logo_image %}{{ configurations.logo_image.url }}
                    {% else %}{% static 'assets/img/logo_footer.png' %}{% endif %}" alt="logo_footer.png"/>
                </a>
            </div>
            <div class="row-block">
                <strong class="Footer-title">Навигация</strong>
                <ul class="menu menu_vt Footer-menu">
                    <li class="menu-item"><a class="menu-link" href="{% url 'index' %}">Главная</a></li>
                    <li class="menu-item"><a class="menu-link" href="{% url 'catalog:catalog' %}">Каталог</a></li>
                    <li class="menu-item"><a class="menu-link" href="{% url 'private_office:profile' %}">Профиль</a></li>
                </ul>
            </div>
            <div class="row-block">
                <strong class="Footer-title">Контакты</strong>
                <p>Phone: {% firstof configurations.contact_number '8.800.200.600' %}<br>
                    Email: {% firstof configurations.contact_email 'xxx@meg.com' %}<br>
                </p>
                <ul class="menu menu_img menu_smallImg Footer-menuSoc">
                    <li class="menu-item">
                        <a class="menu-link" href="#">
                            <img src="{% static 'assets/img/icons/socialFooter/fb.svg' %}" alt="fb.svg"/>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">
                            <img src="{% static 'assets/img/icons/socialFooter/tw.svg' %}" alt="tw.svg"/>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">
                            <img src="{% static 'assets/img/icons/socialFooter/in.svg' %}" alt="in.svg"/>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">
                            <img src="{% static 'assets/img/icons/socialFooter/pt.svg' %}" alt="pt.svg"/>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">
                            <img src="{% static 'assets/img/icons/socialFooter/mail.svg' %}" alt="mail.svg"/>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

store/my_store_app/templates/includes/head_line.html
{% load static %}

<div class="ControlPanel">
    <div class="wrap">
        <div class="row ControlPanel-row">
            <div class="row-block">
                <div class="row ControlPanel-rowSplit">
                    <div class="row-block hide_700">


                                <!--           Ссылки на соц-сети            -->
                        <ul class="menu menu_img menu_smallImg ControlPanel-menu">
                            <li class="menu-item">
                                <a class="menu-link" href="#">
                                    <img src="{% static 'assets/img/icons/socialHeader/tw.svg' %}" alt="tw.svg"/>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a class="menu-link" href="#">
                                    <img src="{% static 'assets/img/icons/socialHeader/in.svg' %}" alt="in.svg"/>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a class="menu-link" href="#">
                                    <img src="{% static 'assets/img/icons/socialHeader/pt.svg' %}" alt="pt.svg"/>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a class="menu-link" href="#">
                                    <img src="{% static 'assets/img/icons/socialHeader/mail.svg' %}" alt="mail.svg"/>
                                </a>
                            </li>
                        </ul>


                    </div>
                </div>
            </div>
            <nav class="row-block">
                <div class="row ControlPanel-rowSplit">
                    {% if user.is_authenticated %}
                        <div class="row-block">
                            <a class="ControlPanel-title" href="{% url 'private_office:office' %}">Личный кабинет</a>
                            <a class="ControlPanel-title" href="{% url 'user_app:logout' %}">Выход</a>
                            <p class="ControlPanel-title">{{ user.username }}</p>
                        </div>
                    {% else %}
                        <div class="row-block">
                            <a class="ControlPanel-title" href="{% url 'user_app:login' %}">Вход</a>
                            <a class="ControlPanel-title" href="#modal_open_register">Регистрация</a>
                        </div>
                        <div id="modal_open_register" class="my_modal">
                            <div class="my_modal-dialog">
                                <div class="my_modal-content">
                                    <div class="my_modal-header">
                                        <p class="my_modal-title" align="center">Регистрация</p>
                                        <a href="#" title="Закрыть модальное окно" class="close">×</a>
                                    </div>
                                    <div class="my_modal-body">
                                        <a style="float: left" class="ControlPanel-title" href="{% url 'user_app:register_customer' %}">Покупатель</a>
                                        <a style="float: right; margin: 0px; margin-right:30px;" class="ControlPanel-title" href="{% url 'user_app:register_seller_step_one' %}">Продавец</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </nav>
        </div>
    </div>
    <!--+div.menuModal#navigate
//    +menu([
//        ['Главная','index.html'],
//        ['Портфолио','index.html'],
//        ['Мои проекты','index.html'],
//        ['Контакты','index.html']
//    ], page === 'article'? 'Портфолио': 'Главная')._main

block
-->
</div>

store/my_store_app/templates/includes/header.html
{% load static %}

<meta name="description" content="Описание страницы">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
<link href="{% static 'favicon.ico' %}" rel="shortcut icon">
<link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
<link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
<link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
<link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
<link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
<link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
<link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/extra.css' %}">
<script src="{% static 'assets/plg/CountDown/countdown.js' %}"></script>
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

store/my_store_app/templates/includes/search-line.html
{% load static %}
{% load my_tags %}


<div class="Header-searchWrap">
    <div class="wrap">

        <!--    Отображение меню категорий    -->
        {% head_categories active_categories %}

        <div class="Header-searchLink">
            <img src="{% static 'assets/img/icons/search.svg' %}" alt="search.svg"/>
        </div>
        <div class="Header-search">
            <div class="search">
                <form class="form form_search" action="#" method="post">
                    {% csrf_token %}
                    <input class="search-input" id="query" name="query" type="text"
                           placeholder="NVIDIA GeForce RTX 3060"/>
                    <button class="search-button" type="submit" name="search" id="search">
                        <img src="{% static 'assets/img/icons/search.svg' %}" alt="search.svg"/>Поиск
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

store/my_store_app/templates/includes/top-menu-and-logo.html
{% load static %}

<div class="wrap">
    <div class="row Header-rowMain">
        <div class="row-block Header-logo">
            <a class="logo" href="{% url 'index' %}">
                <img class="logo-image"
                     src="{% if configurations.logo_image %}{{ configurations.logo_image.url }}{% else %}{% static 'assets/img/logo.png' %}{% endif %}"
                     alt="logo.png"/>
            </a>
        </div>
        <nav class="row-block row-block_right Header-menu">
            <div class="menuModal" id="navigate">
                <ul class="menu menu_main">
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'index' %}">Главная</a>
                    </li>
                    <li class="menu-item">
                        <span class="menu-label menu-label_success">Скидки</span>
                        <a class="menu-link" href="{% url 'catalog:catalog' %}">Каталог</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="row-block">
            <div class="CartBlock">
                {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="dropbtn">
                        <img class="CartBlock-img" src="{% static 'assets/img/icons/loon-icon.svg' %}"
                             alt="loon-icon.svg"/>
                    </button>
                    <div class="dropdown-content">
                        <a class="dropdown-content-a" href="{% url 'private_office:office' %}">Личный кабинет</a>
                        <a class="dropdown-content-a" href="{% url 'admin:login' %}">Административный раздел</a>
                        <a class="dropdown-content-a" href="{% url 'user_app:logout' %}">Выход</a>
                    </div>
                </div>
                {% endif %}
                <a class="CartBlock-block" href="{% url 'cart:cart' %}">
                    <img class="CartBlock-img" src="{% static 'assets/img/icons/cart.svg' %}" alt="cart.svg"/>
                    <span class="CartBlock-amount">{% if not quantity_of_goods %}0{% else %}{{ quantity_of_goods }}{% endif %}</span>
                </a>
                <div class="CartBlock-block">
                    <span class="CartBlock-price">{% if not sum %}0.00{% else %}{{ sum }}{% endif %}$</span>
                </div>
            </div>
        </div>
        <div class="row-block Header-trigger">
            <a class="menuTrigger" href="#">
                <div class="menuTrigger-content">Показать навигацию</div>
            </a>
        </div>
    </div>
</div>