store/cart/urls.py
from django.urls import path
from .views import CartView


app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
]

store/catalog/urls.py
from django.urls import path
from .views import CatalogView


app_name = 'catalog'

urlpatterns = [
    path('', CatalogView.as_view(), name='catalog'),
]

store/ordering/urls.py
from django.urls import path
from .views import OrderViewStep1, OrderViewStep2, OrderViewStep3, OrderViewStep4, PaymentOnlineCardView, PaymentSomeoneCardView, OrderDetails


app_name = 'order'

urlpatterns = [
    path('step-1/', OrderViewStep1.as_view(), name='step_1'),
    path('step-2/', OrderViewStep2.as_view(), name='step_2'),
    path('step-3/', OrderViewStep3.as_view(), name='step_3'),
    path('step-4/', OrderViewStep4.as_view(), name='step_4'),
    path('payment-online/', PaymentOnlineCardView.as_view(), name='payment_online'),
    path('payment-someone/', PaymentSomeoneCardView.as_view(), name='payment_someone'),
    path('details/<int:pk>/', OrderDetails.as_view(), name='order_details'),
]

store/private_office/urls.py
from django.urls import path
from .views import office, profile, HistoryView, delete_avatar


app_name = 'private_office'

urlpatterns = [
    path('', office, name='office'),
    path('profile/', profile, name='profile'),
    path('history/', HistoryView.as_view(), name='history'),
    path('del-avatar/', delete_avatar, name='del_avatar'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from my_store_app.views import CategoryView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user-auth/', include("user_app.urls")),
    path('catalog/', include("catalog.urls")),
    path('cart/', include("cart.urls")),
    path('details/', include("product_details.urls")),
    path('private-office/', include("private_office.urls")),
    path('order/', include("ordering.urls")),
    path('', CategoryView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/private_office/models.py
from django.db import models

# Create your models here.

store/private_office/forms.py
from django import forms
from customers_sellers.models import Profile
from my_store_app.utils import validate_image

class ChangeProfileInfoFormLeft(forms.ModelForm):
    avatar = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'Profile-file form-input'}),
                              validators=[validate_image], label='Аватар')

    class Meta:
        model = Profile
        fields = ['avatar', 'name', 'family_name', 'surname']


class ChangeProfileInfoFormRight(forms.Form):
    phone = forms.CharField(label='Телефон', required=False)
    email = forms.EmailField(label='E-mail', required=False)
    password1 = forms.CharField(widget=forms.PasswordInput(), label='Пароль', required=False)
    password2 = forms.CharField(widget=forms.PasswordInput(), label='Повторите пароль', required=False)

store/private_office/views.py
from customers_sellers.utils import remove_previous_image
from django.contrib import messages
from django.contrib.auth import decorators
from django.contrib.auth.models import User
from django.forms import model_to_dict
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.views.generic import ListView
from customers_sellers.models import Profile
from ordering.models import Order
from .forms import ChangeProfileInfoFormLeft, ChangeProfileInfoFormRight
from my_store_app.utils import total_sum_and_quantity_update_context
from cart.service import CartService
from django.contrib.auth.mixins import LoginRequiredMixin



@decorators.login_required
def office(request):
    cart_service = CartService(request=request)
    queryset = cart_service.get_list_of_products_in_cart(request=request)
    user = request.user

    flag_for_payment = order_continue_flag = False
    if hasattr(user, 'order'):
        order = user.order
        if order.error_message:
            flag_for_payment = True
        elif order.status == 'not_paid':
            order_continue_flag = True
    else:
        # Если активного заказа у пользователя нет, то выбирается последний(по дате оплаты) заказ и отображается в личном кабинете
        order = Order.objects.filter(history_user=user, user__isnull=True).order_by('-payment_date').first()

    context = {
        'menu_item': 'Личный кабинет',
        'order': order,
        'flag_for_payment': flag_for_payment,
        'order_continue_flag': order_continue_flag,
    }

    if hasattr(user, 'customer'):
        user_profile = user.customer.profile
        user_profile_opts = user_profile._meta

        default_values_dict = {
            'name_default_value': user_profile_opts.get_field('name').default,
            'family_name_default_value': user_profile_opts.get_field('family_name').default,
            'surname_default_value': user_profile_opts.get_field('surname').default,
        }

        context.update(default_values_dict)

    total_sum_and_quantity_update_context(context=context, request=request, queryset_for_cart_table=queryset)

    return render(request, 'private_office/account.html', context)


@decorators.login_required
def profile(request: HttpRequest):
    cart_service = CartService(request=request)
    queryset = cart_service.get_list_of_products_in_cart(request=request)
    avatar = request.FILES.get('avatar')

    if request.method == 'POST':
        #POST запрос
        post_dict = request.POST.copy()
        post_dict['phone'] = post_dict.get('phone')[3:].replace(')', '-')

        form_left = ChangeProfileInfoFormLeft(post_dict, request.FILES)
        form_right = ChangeProfileInfoFormRight(post_dict)
        if form_left.is_valid() and form_right.is_valid():
            user: User = request.user

            profile_user = Profile.objects.filter(customer=user.customer).first()
            profile_user.name = form_left.cleaned_data['name']
            profile_user.family_name = form_left.cleaned_data['family_name']
            profile_user.surname = form_left.cleaned_data['surname']
            profile_user.phone = form_right.cleaned_data['phone']
            profile_user.email = form_right.cleaned_data['email']

            if avatar:
                remove_previous_image(media_path=profile_user.avatar.name)
                profile_user.avatar = avatar
            profile_user.save()

            messages.add_message(request=request, level=messages.SUCCESS,
                                 message='Данные профиля успешно сохранены.')

            if form_right.cleaned_data['password1']:
                first_pass = form_right.cleaned_data['password1']
                second_pass = form_right.cleaned_data['password2']
                if first_pass == second_pass:
                    user.set_password(first_pass)
                    user.save()
                    messages.add_message(request=request, level=messages.SUCCESS,
                                         message='Пароль изменён успешно.')
                else:
                    form_right.add_error('password2', 'Пароли не совпадают')
                    messages.add_message(request=request, level=messages.WARNING,
                                         message='Пароль не был изменён.')

        context = {
            'menu_item': 'Профиль',
            'left_form': form_left,
            'right_form': form_right,
        }
        total_sum_and_quantity_update_context(context=context, request=request, queryset_for_cart_table=queryset)

        return render(request, 'private_office/profile.html', context)

    #GET запрос
    profile_inst = request.user.customer.profile
    profile_dict = model_to_dict(profile_inst, fields=['name', 'family_name', 'surname', 'phone', 'email', 'avatar'])
    context = {
        'menu_item': 'Профиль',
        'left_form': ChangeProfileInfoFormLeft(profile_dict),
        'right_form': ChangeProfileInfoFormRight(profile_dict)
    }
    total_sum_and_quantity_update_context(request=request, context=context, queryset_for_cart_table=queryset)

    return render(request, 'private_office/profile.html', context)


class HistoryView(LoginRequiredMixin, ListView):
    template_name = 'private_office/historyorder.html'
    model = Order
    context_object_name = 'orders'

    def get_queryset(self):
        queryset = super().get_queryset().filter(user__isnull=True, history_user=self.request.user).order_by('-payment_date')
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        cart_service = CartService(request=self.request)
        context = super().get_context_data(object_list=None, **kwargs)
        context['menu_item'] = 'История заказов'
        total_sum_and_quantity_update_context(
            context=context,
            request=self.request,
            queryset_for_cart_table=cart_service.get_list_of_products_in_cart(request=self.request)
        )
        return context


@decorators.login_required
def delete_avatar(request: HttpRequest):
    profile_obj = request.user.customer.profile
    if profile_obj.avatar:
        remove_previous_image(profile_obj.avatar.name)
        profile_obj.avatar = ''
        profile_obj.save()
        messages.add_message(request=request, level=messages.SUCCESS, message='Аватар успешно удалён!')
    return redirect('private_office:profile')

store/private_office/templates/private_office/account.html
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->

{% load my_tags %}

<head>
    <title>Private office</title>
    {% include 'includes/header.html' %}
</head>

<body class="Site">
    <!--if lt IE 8
  p.error-browser
      | Ваш браузер&nbsp;
      em устарел!&nbsp;
      a(href="http://browsehappy.com/") Выберите новую версию
          +s
          | браузера здесь&nbsp;
      | для правильного отображения сайта.
  -->
    {% include 'includes/head_line.html' %}
    {% include 'includes/top-menu-and-logo.html' %}
    {% include 'includes/search-line.html' %}

    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">


                <!--        Отображение меню        -->
                {% private_office_menu menu_item %}


                <div class="Section-content">
                    <div class="Account">
                        <div class="Account-group">
                            <div class="Account-column">
                                {% with avatar=user.customer.profile.avatar %}
                                {% if avatar %}
                                <div class="Account-avatar">
                                    <img src="{{ avatar.url }}" alt="card.jpg" />
                                </div>
                                {% endif %}
                                {% endwith %}
                            </div>
                            <div class="Account-column">
                                <div class="Account-name">
                                    {% if user.customer.profile.name != name_default_value %}
                                        {{ user.customer.profile.name }}

                                        {% if user.customer.profile.family_name != family_name_default_value %}
                                            {{ user.customer.profile.family_name }}
                                        {% endif %}

                                        {% if user.customer.profile.surname != surname_default_value %}
                                            {{ user.customer.profile.surname }}
                                        {% endif %}
                                    {% else %}
                                        {{ user.username }}
                                    {% endif %}
                                </div>
                                <a class="Account-editLink" href="{% url 'private_office:profile' %}">Редактировать профиль</a>
                            </div>
                        </div>
                        <div class="Account-group">
                            {% if order %}
                            <div class="Account-column Account-column_full">
                                <div class="Order Order_anons">
                                    <div class="Order-personal">
                                        <div class="row">
                                            <div class="row-block">
                                                <a class="Order-title" href="{{ order.get_absolute_url }}">
                                                    Заказ&#32;
                                                    <span class="Order-numberOrder">№{{ order.id }}</span>
                                                    &#32;от&#32;
                                                    <span class="Order-dateOrder">{{ order.payment_date|date:"d.m.Y" }}</span>
                                                </a>
                                                {% if flag_for_payment %}
                                                <div class="Account-editLink">
                                                    <a style="font-size: 19px; color: #fd4f64" href="{% url 'order:step_4' %}">Попробовать оплатить снова</a>
                                                </div>
                                                {% endif %}
                                                <div class="Account-editLink">
                                                    <a href="{% url 'private_office:history' %}">История заказов</a>
                                                </div>
                                            </div>
                                            <div class="row-block">
                                                <div class="Order-info Order-info_delivery">
                                                    <div class="Order-infoType">Тип доставки:</div>
                                                    <div class="Order-infoContent">{{ order.get_delivery_method_display }}{% if order.delivery_price %}(+{{ order.delivery_price }}р){% endif %}</div>
                                                </div>
                                                <div class="Order-info Order-info_pay">
                                                    <div class="Order-infoType">Оплата:</div>
                                                    <div class="Order-infoContent">{{ order.get_pay_method_display }}</div>
                                                </div>
                                                <div class="Order-info">
                                                    <div class="Order-infoType">Общая стоимость:</div>
                                                    <div class="Order-infoContent">{{ order.total_price }}$</div>
                                                </div>
                                                <div class="Order-info Order-info_status">
                                                    <div class="Order-infoType">Статус:</div>
                                                    <div class="Order-infoContent">{{ order.get_status_display }}</div>
                                                </div>
                                                {% if order.error_message %}
                                                <div class="Order-info Order-info_status">
                                                    <div class="Order-infoType">Ошибка:</div>
                                                    <div class="Order-infoContent">{{ order.error_message|truncatechars:25 }}</div>
                                                </div>
                                                {% endif %}
                                            </div>
                                        </div>
                                        {% if order_continue_flag %}
                                            <div class="Account-editLink" align="center" style="margin-top: 30px">
                                                <a style="font-size: 19px;" href="{% url 'order:step_1' %}">Продолжить оформление заказа</a>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--+Middle-->
    <!--    +div.-top-->
    <!--        +breadcrumbs('Главная','Портфолио')-->
    <!--    +Article('portfolio')-->
    <!---->
    {% include 'includes/footer.html' %}
    {% include 'includes/bottom_scripts.html' %}
</body>

</html>

store/private_office/templates/private_office/historyorder.html
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->

{% load my_tags %}

<head>
    <title>Megano</title>
    {% include 'includes/header.html' %}
</head>

<body class="Site">
<!--if lt IE 8
p.error-browser
  | Ваш браузер&nbsp;
  em устарел!&nbsp;
  a(href="http://browsehappy.com/") Выберите новую версию
      +s
      | браузера здесь&nbsp;
  | для правильного отображения сайта.
-->
{% include 'includes/head_line.html' %}
{% include 'includes/top-menu-and-logo.html' %}
{% include 'includes/search-line.html' %}
<div class="Middle Middle_top">
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">


            <!--        Отображение меню        -->
            {% private_office_menu menu_item %}


            <div class="Section-content">
                <div class="Orders">
                    {% for order in orders %}
                    <div class="Order Order_anons">
                        <div class="Order-personal">
                            <div class="row">
                                <div class="row-block">
                                    <a class="Order-title" href="{{ order.get_absolute_url }}">
                                        Заказ&#32;
                                        <span class="Order-numberOrder">№{{ order.id }}</span>
                                        &#32;от&#32;
                                        <span class="Order-dateOrder">{{ order.payment_date|date:'d.m.Y' }}</span>
                                    </a>
                                </div>
                                <div class="row-block">
                                    <div class="Order-info Order-info_delivery">
                                        <div class="Order-infoType">Тип доставки:</div>
                                        <div class="Order-infoContent">{{ order.get_delivery_method_display }}</div>
                                    </div>
                                    <div class="Order-info Order-info_pay">
                                        <div class="Order-infoType">Оплата:</div>
                                        <div class="Order-infoContent">{{ order.get_pay_method_display }}</div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">Общая стоимость:</div>
                                        <div class="Order-infoContent">
                                            <span class="Order-price">{{ order.total_price }}$</span>
                                        </div>
                                    </div>
                                    <div class="Order-info Order-info_status">
                                        <div class="Order-infoType">Статус:</div>
                                        <div class="Order-infoContent">{{ order.get_status_display }}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                        <div align="center">
                            История заказов пока пуста.<br>
                            Начните заполнять корзину <a href="{% url 'catalog:catalog' %}">здесь</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'includes/footer.html' %}
{% include 'includes/bottom_scripts.html' %}
<!--+Middle-->
<!--    +div.-top-->
<!--        +breadcrumbs('Главная','Портфолио')-->
<!--    +Article('portfolio')-->
<!---->
</body>

</html>

store/private_office/templates/private_office/profile.html
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->

{% load static %}
{% load my_tags %}

<head>
    <title>Private office</title>
    {% include 'includes/header.html' %}
</head>

<body class="Site">
    <!--if lt IE 8
  p.error-browser
      | Ваш браузер&nbsp;
      em устарел!&nbsp;
      a(href="http://browsehappy.com/") Выберите новую версию
          +s
          | браузера здесь&nbsp;
      | для правильного отображения сайта.
  -->
    {% include 'includes/head_line.html' %}
    {% include 'includes/top-menu-and-logo.html' %}
    {% include 'includes/search-line.html' %}

    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">


                <!--        Отображение меню        -->
                {% private_office_menu menu_item %}

                <div class="Section-content">
                    <div class="Profile">
                        <form class="form Profile-form" method="post" enctype="multipart/form-data">
                            <div class="row">

                                <div class="row-block">
                                    {% if left_form.non_field_errors %}
                                        {% for error in left_form.non_field_errors %}
                                            <div style="color: red;">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}

                                    {% for field in left_form %}
                                        {% if field.errors %}
                                            {% for error in field.errors %}
                                                <div style="color: red;">{{ error }}</div>
                                            {% endfor %}
                                        {% endif %}

                                        {% if forloop.counter == 1 %}
                                            {% with profile=user.customer.profile %}
                                            <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                            {% if not profile.avatar %}
                                            <div class="Profile-avatar Profile-avatar_noimg" style="height: 289px; margin-bottom: 25px;">
                                                <label class="Profile-fileLabel" for="{{ field.id_for_label }}">
                                                    <img src="{% static 'assets/img/icons/upload.png' %}" alt="avatar.png" />Загрузить фото
                                                </label>
                                                {{ field }}
                                            </div>
                                            {% else %}
                                                <div style="height: 289px; margin-bottom: 25px;">
                                                    <img style="height: 100%; width: 100%" src="{{ profile.avatar.url }}" alt="avatar.png" />
                                                </div>
                                            {% endif %}
                                            {% endwith %}
                                        {% else %}
                                        <div class="form-group">
                                            <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                            {{ field }}
                                        </div>
                                        {% endif %}
                                    {% endfor %}
                                </div>

                                <div class="row-block">
                                    {% if right_form.non_field_errors %}
                                        {% for error in right_form.non_field_errors %}
                                            <div style="color: red;">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}

                                    {% for field in right_form %}
                                    {% if field.errors %}
                                        {% for error in field.errors %}
                                            <div style="color: red;">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                    <div class="form-group">
                                        <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                        {{ field }}
                                    </div>
                                    {% endfor %}

                                    {% with avatar=user.customer.profile.avatar %}
                                    <div class="form-group">
                                        <div class="Profile-btn">
                                            {% csrf_token %}
                                            <div style="display: flex; justify-content: space-between;">
                                                {% if avatar %}
                                                    <input type="hidden" name="delete_avatar">
                                                    <a class="btn" style="color: red" href="{% url 'private_office:del_avatar' %}">Удалить аватар</a>
                                                {% endif %}
                                                <button class="btn btn_success" type="submit">Сохранить</button>
                                            </div>

                                        </div>

                                        {% for message in messages %}
                                            {% if message.tags == 'success' %}
                                            <div class="Profile-success">{{ message }}</div>
                                            {% endif %}
                                        {% endfor %}
                                        {% for message in messages %}
                                            {% if message.tags == 'warning' %}
                                            <div class="Profile-success" style="color:red">{{ message }}</div>
                                            {% endif %}
                                        {% endfor %}

                                    </div>
                                    {% endwith %}
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery.maskedinput@1.4.1/src/jquery.maskedinput.js" type="text/javascript"></script>
    <script>
        $("#id_phone").mask("+7(999)999-99-99");
    </script>
    {% include 'includes/footer.html' %}
    <!--+Middle-->
    <!--    +div.-top-->
    <!--        +breadcrumbs('Главная','Портфолио')-->
    <!--    +Article('portfolio')-->
    <!---->
    {% include 'includes/bottom_scripts.html' %}
</body>

</html>