store/cart/urls.py
from django.urls import path
from .views import CartView


app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from my_store_app.views import CategoryView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user-auth/', include("user_app.urls")),
    path('catalog/', include("catalog.urls")),
    path('cart/', include("cart.urls")),
    path('details/', include("product_details.urls")),
    path('private-office/', include("private_office.urls")),
    path('order/', include("ordering.urls")),
    path('', CategoryView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/user_app/urls.py
from django.urls import path
from .views import (Login, AuthorLogoutView, RegisterCustomerView, FirstRegisterSellerView, SecondRegisterSellerView,
                    RestorePasswordFirstStep,
                    RestorePasswordSecondStep)


app_name = 'user_app'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', AuthorLogoutView.as_view(), name='logout'),
    path('register/customer/', RegisterCustomerView.as_view(), name='register_customer'),
    path('register/seller/first-step', FirstRegisterSellerView.as_view(), name='register_seller_step_one'),
    path('register/seller/second-step', SecondRegisterSellerView.as_view(), name='register_seller_step_two'),
    path('register/drop-password/first-step/', RestorePasswordFirstStep.as_view(), name='password_first'),
    path('register/drop-password/second-step/', RestorePasswordSecondStep.as_view(), name='password_second'),
]

store/user_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    is_store = models.BooleanField(default=False, verbose_name='Владелец магазина')
    phone = models.CharField(max_length=30, unique=True, verbose_name='Номер телефона')
    email = models.EmailField(unique=True, verbose_name='Электронная почта')

store/user_app/forms.py
from django import forms


class CustomerRegisterForm(forms.Form):
    name = forms.CharField(required=False, help_text='имя пользователя',
                                widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': 'Имя(необязательно)'}))
    family_name = forms.CharField(required=False, help_text='фамилия пользователя',
                           widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': 'Фамилия(необязательно)'}))
    surname = forms.CharField(required=False, help_text='отчество пользователя',
                                  widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': 'Отчество(необязательно)'}))
    phone = forms.CharField(required=True, help_text='номер телефона',
                            widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': '*Телефон'}))
    email = forms.EmailField(required=True,  help_text='email',
                             widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': '*E-mail'}))
    login = forms.CharField(required=True, help_text='логин',
                            widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': '*Логин'}))
    password = forms.CharField(required=True, help_text='пароль',
                               widget=forms.PasswordInput(attrs={'class': 'user-input', 'placeholder': '*Пароль'}))


class FirstSellerRegisterForm(forms.Form):
    owner_name = forms.CharField(required=False, help_text='имя пользователя',
                                widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': 'Имя(необязательно)'}))
    owner_family_name = forms.CharField(required=False, help_text='фамилия пользователя',
                           widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': 'Фамилия(необязательно)'}))
    owner_surname = forms.CharField(required=False, help_text='отчество пользователя',
                                  widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': 'Отчество(необязательно)'}))
    phone = forms.CharField(required=True, help_text='номер телефона',
                            widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': '*Телефон'}))
    email = forms.EmailField(required=True,  help_text='email',
                             widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': '*E-mail'}))
    username = forms.CharField(required=True, help_text='логин',
                            widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': '*Логин'}))
    password = forms.CharField(required=True, help_text='пароль',
                               widget=forms.PasswordInput(attrs={'class': 'user-input', 'placeholder': '*Пароль'}))


class SecondSellerRegisterForm(forms.Form):
    shop_name = forms.CharField(required=True, help_text='Название вашего магазина',
                            widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': '*Название магазина'}))
    address = forms.CharField(required=True, help_text='Адрес магазина',
                            widget=forms.TextInput(attrs={'class': 'user-input', 'placeholder': '*Адрес магазина'}))


class FirstStepForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'E-mail'}))

store/user_app/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from .forms import CustomerRegisterForm, FirstSellerRegisterForm, SecondSellerRegisterForm, FirstStepForm
from customers_sellers.models import Profile, Customer, ShopInfo, Shop
from django.contrib.auth import login
from goods.models import ProductShopRelations
from cart.service import CartService
from .utils import validate_user_data


class Login(LoginView):
    """Вход в учетную запись"""

    template_name = 'user_app/login.html'
    redirect_authenticated_user = True

    def form_valid(self, form):
        login(self.request, form.get_user())

        # Слияние корзин
        session_cart = self.request.session.get('cart')
        if session_cart:
            service = CartService(request=self.request)
            product_shop = ProductShopRelations.objects.filter(pk__in=service.cart.keys())
            for item in product_shop:
                service.add_product_to_cart(product_shop=item, request=self.request, quantity=service.cart[str(item.id)]['quantity'])
        try:
            del self.request.session['cart']
        except:
            pass

        if 'log' in self.request.POST:
            return redirect(reverse('order:step_1'))

        return HttpResponseRedirect(self.get_success_url())


class AuthorLogoutView(LogoutView):
    """Выход из учетной записи"""
    next_page = reverse_lazy('index')


class RegisterCustomerView(View):
    """Представление для регистрации пользователей и магазинов"""

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('index')

        form = CustomerRegisterForm()
        return render(request, 'user_app/register.html', context={'form': form})

    def post(self, request: HttpRequest, *args, **kwargs):
        form = CustomerRegisterForm(request.POST)
        phone = request.POST['phone'][3:].replace(')', '-')
        email, username = request.POST['email'], request.POST['login']
        user_model = get_user_model()

        validate_user_data(user=user_model, form=form, username=username, email=email, phone=phone)

        if 'password2' in request.POST:
            pass1 = request.POST.get('password')
            pass2 = request.POST.get('password2')
            if not pass1 == pass2:
                request.session['error_password'] = request.POST
                url = reverse('order:step_1')
                return redirect(url)

        if form.is_valid():
            new_user = user_model.objects.create_user(
                username=form.cleaned_data['login'],
                password=form.cleaned_data['password'],
                phone=phone,
                email=form.cleaned_data['email']
            )

            customer = Customer.objects.create(user=new_user)

            Profile.objects.create(
                customer=customer,
                name=form.cleaned_data['name'] if form.cleaned_data['name'] else Profile._meta.get_field('name').default,
                family_name=form.cleaned_data['family_name'] if form.cleaned_data['family_name'] else Profile._meta.get_field('family_name').default,
                surname=form.cleaned_data['surname'] if form.cleaned_data['surname'] else Profile._meta.get_field('surname').default,
            )

            if 'reg' in request.POST:
                url = reverse('order:step_1') + '#open_auth_modal'
                return redirect(url)

            return redirect('index')

        if 'reg' in request.POST:
            url = reverse('order:step_1') + '#open_auth_modal_already_exists'
            return redirect(url)

        return render(request, 'user_app/register.html', context={'form': form})


class FirstRegisterSellerView(View):
    """Представление для регистрации магазина и владельца этого магазина"""

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('index')

        # заполнение существующими данными, формы регистрации
        user_data = request.session.get('owner_data')
        if user_data is not None:
            form = FirstSellerRegisterForm(user_data)
        else:
            form = FirstSellerRegisterForm()

        return render(request, 'user_app/register_seller_first.html', context={'form': form})

    def post(self, request: HttpRequest, *args, **kwargs):
        form = FirstSellerRegisterForm(request.POST)
        phone = request.POST['phone'][3:].replace(')', '-')
        email, username = request.POST['email'], request.POST['username']
        user = get_user_model()

        validate_user_data(user=user, form=form, username=username, email=email, phone=phone)

        if form.is_valid():
            # подготовка к созданию пользователя
            # занесение всех необходимых данных в сессию
            request.session['owner_data'] = form.cleaned_data

            return redirect('user_app:register_seller_step_two')

        return render(request, 'user_app/register_seller_first.html', context={'form': form})


class SecondRegisterSellerView(View):
    """Представление для регистрации магазина и владельца этого магазина"""

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated or not request.session.get('owner_data'):
            return redirect('index')

        form = SecondSellerRegisterForm()
        return render(request, 'user_app/register_seller_second.html', context={'form': form})

    def post(self, request: HttpRequest, *args, **kwargs):
        form = SecondSellerRegisterForm(request.POST)

        if form.is_valid():
            d = request.session['owner_data']

            # создание пользователя из данных сессии
            owner_user = get_user_model().objects.create_user(
                username=d['username'],
                password=d['password'],
                email=d['email'],
                phone=d['phone'],
                is_store=True,
            )

            # привязка магазина к владельцу
            shop = Shop.objects.create(owner=owner_user)

            # привязка дополнительной информации к магазину
            ShopInfo.objects.create(
                shop=shop,
                owner_name=d['owner_name'] if d['owner_name'] else ShopInfo._meta.get_field('owner_name').default,
                owner_family_name=d['owner_family_name'] if d['owner_family_name'] else ShopInfo._meta.get_field('owner_family_name').default,
                owner_surname=d['owner_surname'] if d['owner_surname'] else ShopInfo._meta.get_field('owner_surname').default,
                **form.cleaned_data
            )

            return redirect('index')

        return render(request, 'user_app/register_seller_first.html', context={'form': form})


class RestorePasswordFirstStep(View):
    """Класс для сброса пароля"""

    def get(self, request):

        context = {
            'form': FirstStepForm()
        }

        return render(request, 'user_app/password-first-step.html', context=context)

    def post(self, request):
        form = FirstStepForm(request.POST)
        if form.is_valid():
            user = User.objects.filter(customer__profile__email=form.cleaned_data['email']).first()
            if not user:
                messages.add_message(request=request, level=messages.WARNING, message='Пользователя с такой почтой не существует. Попробуйте ещё раз.')
                return render(request, 'user_app/password-first-step.html', context={'form': form})

            request.session['user_identifier'] = user.id
            return redirect('user_app:password_second')

        return render(request, 'user_app/password-first-step.html', context={'form': form})


class RestorePasswordSecondStep(View):
    def get(self, request):
        if not request.session.get('user_identifier'):
            messages.add_message(request=request, level=messages.WARNING, message='Сначала укажите почту для восстановления пароля')
            return render(request, 'user_app/password-first-step.html', context={'form': FirstStepForm()})

        return render(request, 'user_app/password-second-step.html')

    def post(self, request):
        if not request.session.get('user_identifier'):
            return self.get(request=request)

        id_user = request.session.get('user_identifier')
        user = User.objects.get(id=id_user)
        raw_password = request.POST.get('pass')
        if not raw_password:
            messages.add_message(request, messages.WARNING, 'Введите пароль!')
            return self.get(request=request)

        user.set_password(raw_password=raw_password)
        user.save()

        try:
            del request.session['user_identifier']
        except:
            pass

        return redirect('user_app:login')

store/user_app/templates/user_app/login.html
<!--END-->
{% load static %}
<!--END-->
<!DOCTYPE html>

<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->

<head>
    <title>Login</title>
    {% include 'includes/header.html' %}
</head>

<body class="Site">
<!--if lt IE 8
p.error-browser
  | Ваш браузер&nbsp;
  em устарел!&nbsp;
  a(href="http://browsehappy.com/") Выберите новую версию
      +s
      | браузера здесь&nbsp;
  | для правильного отображения сайта.
-->
<main class="Middle" style="margin-top: 0px;">
    {% include 'includes/head_line.html' %}
    <div class="wrap">
        <div class="row Header-rowMain">
            <div class="row-block Header-logo">
                <a class="logo" href="{% url 'index' %}">
                    <img class="logo-image" src="{% static 'assets/img/logo.png' %}" alt="logo.png"/>
                </a>
            </div>
        </div>
        <div class="wrapper">
            <div class="header">
                <h3 class="sign-in">Вход</h3>
            </div>
            <form method="post">
                {% csrf_token %}

                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <div style="color:red">{{ error }}</div>
                    {% endfor %}
                {% endif %}

                {% for field in form %}
                    <div>{{ field }}</div>
                {% endfor %}

                <div>
                    <input type="submit" value="Войти"/>
                </div>
                <a class="forgot-label" href="{% url 'user_app:password_first' %}">Забыли пароль?</a>
                <a class="registr" href="{% url 'index' %}#modal_open_register">Регистрация</a>
            </form>
        </div>
    </div>
</main>
{% include 'includes/footer.html' %}
<!--+Middle-->
<!--    +div.-top-->
<!--        +breadcrumbs('Главная','Портфолио')-->
<!--    +Article('portfolio')-->
<!---->
{% include 'includes/bottom_scripts.html' %}
</body>

</html>

store/user_app/templates/user_app/password-first-step.html
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->
{% load static %}

<head>
    <title>Megano</title>
    {% include 'includes/header.html' %}
</head>

<body class="Site">
<!--if lt IE 8
p.error-browser
  | Ваш браузер&nbsp;
  em устарел!&nbsp;
  a(href="http://browsehappy.com/") Выберите новую версию
      +s
      | браузера здесь&nbsp;
  | для правильного отображения сайта.
-->
<header class="Header">
    {% include 'includes/head_line.html' %}
    <div class="wrap">
        <div class="row Header-rowMain">
            <div class="row-block Header-logo">
                <a class="logo" href="{% url 'index' %}">
                    <img class="logo-image" src="{% static 'assets/img/logo.png' %}" alt="logo.png"/></a>
            </div>
        </div>

        <div class="wrapper">
            <div class="header">
                <h3 class="sign-in">Восстановление пароля (1/2)</h3>
                <h5 align="center">Введите свой email</h5>
            </div>

            <form method="post">
                {% csrf_token %}
                {% if messages %}
                    <ul style="font-family: 'Roboto', sans-serif; padding: 0px">
                        {% for message in messages %}
                        <li style="color: red">
                            {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                {% endif %}

                <form method="post">
                    {% for error in form.email.errors %}
                        <div style="color: red;">
                            {{ error }}
                        </div>
                    {% endfor %}
                    {{ form.email }}
                    <input type="submit" value="Далее"/>
                </form>
            </form>
        </div>

    </div>

</header>
{% include 'includes/footer.html' %}
<!--+Middle-->
<!--    +div.-top-->
<!--        +breadcrumbs('Главная','Портфолио')-->
<!--    +Article('portfolio')-->
<!---->
{% include 'includes/bottom_scripts.html' %}
</body>
</html>

store/user_app/templates/user_app/password-second-step.html
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->
{% load static %}

<head>
    <title>Megano</title>
    {% include 'includes/header.html' %}
</head>

<body class="Site">
<!--if lt IE 8
p.error-browser
  | Ваш браузер&nbsp;
  em устарел!&nbsp;
  a(href="http://browsehappy.com/") Выберите новую версию
      +s
      | браузера здесь&nbsp;
  | для правильного отображения сайта.
-->
<header class="Header">
    {% include 'includes/head_line.html' %}
    <div class="wrap">
        <div class="row Header-rowMain">
            <div class="row-block Header-logo">
                <a class="logo" href="{% url 'index' %}">
                    <img class="logo-image" src="{% static 'assets/img/logo.png' %}" alt="logo.png"/></a>
            </div>
        </div>

        <div class="wrapper">
            <div class="header">
                <h3 class="sign-in">Восстановление пароля (2/2)</h3>
                <h5 align="center">Придумайте новый пароль для учетной записи</h5>
            </div>

            <form method="post">
                {% csrf_token %}
                <input type="hidden" value="{{ email }}" name="email">
                {% if messages %}
                    <ul style="font-family: 'Roboto', sans-serif; padding: 0px">
                        {% for message in messages %}
                        <li style="color: red">
                            {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <div>
                    <input type="password" name="pass" placeholder="Пароль"/>
                </div>
                <div>
                    <input type="submit" value="Сохранить пароль"/>
                </div>
            </form>
        </div>

    </div>

</header>
{% include 'includes/footer.html' %}
<!--+Middle-->
<!--    +div.-top-->
<!--        +breadcrumbs('Главная','Портфолио')-->
<!--    +Article('portfolio')-->
<!---->
{% include 'includes/bottom_scripts.html' %}
</body>
</html>

store/user_app/templates/user_app/register.html
<!--END-->
<!--END-->
<!DOCTYPE html>
{% load static %}
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->

<head>
    <title>Register</title>
    {% include 'includes/header.html' %}
</head>

<body class="Site">
<!--if lt IE 8
p.error-browser
  | Ваш браузер&nbsp;
  em устарел!&nbsp;
  a(href="http://browsehappy.com/") Выберите новую версию
      +s
      | браузера здесь&nbsp;
  | для правильного отображения сайта.
-->
<main class="Middle" style="margin-top: 0px;">
    {% include 'includes/head_line.html' %}

    <div class="wrap">
        <div class="row Header-rowMain">
            <div class="row-block Header-logo">
                <a class="logo" href="{% url 'index' %}">
                    <img class="logo-image" src="{% static 'assets/img/logo.png' %}" alt="logo.png"/>
                </a>
            </div>
        </div>
        <div class="wrapper">
            <div class="header">
                <h3 class="sign-in">Регистрация</h3>
            </div>
            <form method="post">
                <div>{{ form.non_field_errors }}</div>
                {% csrf_token %}
                {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                        <div style="color: red">{{ error|escape }}</div>
                        {% endfor %}
                    {% endif %}
                <div>{{ field }}</div>
                {% endfor %}
                <input type="submit" value="Зарегистрироваться"/>
                <a class="registr" href="{% url 'user_app:login' %}">Вход</a>
            </form>
        </div>
    </div>
</main>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery.maskedinput@1.4.1/src/jquery.maskedinput.js" type="text/javascript"></script>
    <script>
        $("#id_phone").mask("+7(999)999-99-99");
    </script>
{% include 'includes/footer.html' %}
<!--+Middle-->
<!--    +div.-top-->
<!--        +breadcrumbs('Главная','Портфолио')-->
<!--    +Article('portfolio')-->
<!---->
{% include 'includes/bottom_scripts.html' %}
</body>
</html>

store/user_app/templates/user_app/register_seller_first.html
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->
{% load static %}

<head>
    <title>Megano</title>
    {% include 'includes/header.html' %}
</head>

<body class="Site">
<!--if lt IE 8
p.error-browser
  | Ваш браузер&nbsp;
  em устарел!&nbsp;
  a(href="http://browsehappy.com/") Выберите новую версию
      +s
      | браузера здесь&nbsp;
  | для правильного отображения сайта.
-->
<header class="Header">
    {% include 'includes/head_line.html' %}
    <div class="wrap">
        <div class="row Header-rowMain">
            <div class="row-block Header-logo">
                <a class="logo" href="{% url 'index' %}">
                    <img class="logo-image" src="{% static 'assets/img/logo.png' %}" alt="logo.png"/></a>
            </div>
        </div>
        <div style="color: red; text-align: center">
            Не выходите со страницы, чтобы не потерять прогресс!
        </div>

        <div class="wrapper">
            <div class="header">
                <h3 class="sign-in" style="text-align: center">Регистрация владельца магазина (1/2)</h3>
                <h5 align="center">Укажите свои данные</h5>
            </div>

            <form method="post">
                <div>{{ form.non_field_errors }}</div>
                {% csrf_token %}
                {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                        <div style="color: red">{{ error|escape }}</div>
                        {% endfor %}
                    {% endif %}
                <div>{{ field }}</div>
                {% endfor %}
                <input type="submit" value="Далее"/>
            </form>
        </div>
    </div>

</header>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery.maskedinput@1.4.1/src/jquery.maskedinput.js" type="text/javascript"></script>
<script>
    $("#id_phone").mask("+7(999)999-99-99");
</script>

{% include 'includes/footer.html' %}
<!--+Middle-->
<!--    +div.-top-->
<!--        +breadcrumbs('Главная','Портфолио')-->
<!--    +Article('portfolio')-->
<!---->
{% include 'includes/bottom_scripts.html' %}
</body>
</html>

store/user_app/templates/user_app/register_seller_second.html
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->
{% load static %}

<head>
    <title>Megano</title>
    {% include 'includes/header.html' %}
</head>

<body class="Site">
<!--if lt IE 8
p.error-browser
  | Ваш браузер&nbsp;
  em устарел!&nbsp;
  a(href="http://browsehappy.com/") Выберите новую версию
      +s
      | браузера здесь&nbsp;
  | для правильного отображения сайта.
-->
<header class="Header">
    {% include 'includes/head_line.html' %}
    <div class="wrap">
        <div class="row Header-rowMain">
            <div class="row-block Header-logo">
                <a class="logo" href="{% url 'index' %}">
                    <img class="logo-image" src="{% static 'assets/img/logo.png' %}" alt="logo.png"/></a>
            </div>
        </div>
        <div style="color: red; text-align: center">
            Не выходите со страницы, чтобы не потерять прогресс!
        </div>

        <div style="display: flex; justify-content: center; align-items: center;">
            <a  class="forgot-label" href="{% url 'user_app:register_seller_step_one' %}">Вернуться на первый шаг</a>
        </div>

        <div class="wrapper">
            <div class="header">
                <h3 class="sign-in" style="text-align: center">Регистрация магазина (2/2)</h3>
                <h5 align="center">Укажите данные вашего магазина</h5>
            </div>

            <form method="post">
                <div>{{ form.non_field_errors }}</div>
                {% csrf_token %}
                {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                        <div style="color: red">{{ error|escape }}</div>
                        {% endfor %}
                    {% endif %}
                <div>{{ field }}</div>
                {% endfor %}
                <input type="submit" value="Далее"/>
            </form>
        </div>
    </div>

</header>

{% include 'includes/footer.html' %}
<!--+Middle-->
<!--    +div.-top-->
<!--        +breadcrumbs('Главная','Портфолио')-->
<!--    +Article('portfolio')-->
<!---->
{% include 'includes/bottom_scripts.html' %}
</body>
</html>